services:
  - type: web
    name: verify-bot
    env: node
    repo: https://github.com/joelikes8/Verify-bot.git
    branch: main
    buildCommand: chmod +x build-render.sh && ./build-render.sh
    startCommand: NODE_ENV=production RENDER=true node dist/server/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: ROBLOX_COOKIE
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: PORT
        value: 10000